export const METRICS = [
  {
    key: "top1_accuracy",
    title: "Top-1 Accuracy",
    desc: "Measures exact classification correctness",
    unit: "%",
    higher: true,
  },
  {
    key: "topk_accuracy",
    title: "Top-k Accuracy",
    desc: "Measures near-miss correctness",
    unit: "%",
    higher: true,
  },
  {
    key: "confidence",
    title: "Prediction Confidence",
    desc: "Average model confidence",
    unit: "%",
    higher: true,
  },
  {
    key: "entropy",
    title: "Prediction Entropy",
    desc: "Uncertainty estimation (lower is better)",
    unit: "",
    higher: false,
  },
  {
    key: "latency_ms",
    title: "Mean Inference Latency",
    desc: "Average inference time",
    unit: "ms",
    higher: false,
  },
  {
    key: "median_latency_ms",
    title: "Median Inference Latency",
    desc: "Robust latency estimate",
    unit: "ms",
    higher: false,
  },
  {
    key: "throughput",
    title: "Throughput",
    desc: "Inferences per second",
    unit: "inf/s",
    higher: true,
  },
  {
    key: "cpu_mean",
    title: "Mean CPU Utilization",
    desc: "Average CPU usage during inference",
    unit: "%",
    higher: false,
  },
  {
    key: "cpu_peak",
    title: "Peak CPU Utilization",
    desc: "Maximum CPU usage observed",
    unit: "%",
    higher: false,
  },
  {
    key: "ram_mean",
    title: "Mean RAM Usage",
    desc: "Average memory consumption",
    unit: "MB",
    higher: false,
  },
  {
    key: "ram_peak",
    title: "Peak RAM Usage",
    desc: "Maximum memory consumption",
    unit: "MB",
    higher: false,
  },
  {
    key: "energy_proxy",
    title: "Energy Proxy Score (CPU × Latency)",
    desc: "Approximate inference energy cost",
    unit: "",
    higher: false,
  },
  {
    key: "efficiency_accuracy_latency",
    title: "Efficiency Score (Accuracy ÷ Latency)",
    desc: "Accuracy efficiency per ms",
    unit: "",
    higher: true,
  },
  {
    key: "efficiency_confidence_latency",
    title: "Efficiency Score (Confidence ÷ Latency)",
    desc: "Confidence efficiency per ms",
    unit: "",
    higher: true,
  },
  {
    key: "overall_index",
    title: "Overall Model Performance Index",
    desc: "Composite performance score",
    unit: "",
    higher: true,
  },
]
